sudo: false
language: ruby
rvm:
  - 2.3.1
before_install: gem install bundler -v 1.12.5
script:
  - sh -c 'cd fibonacci && bundle install && bundle exec rake'
notifications:
  email:
    - mguilherme82@gmail.com
